# !/bin/bash

python3 train.py ../../data/rnn_res/coarse_0_ ../../data/train/coarse_train0.txt.char_to_idx ../../data/train/coarse_train0.txt.word_to_idx ../../data/train/coarse_train0.txt.tag_to_idx ../../data/train/coarse_train0.txt.csv ../../data/test/coarse_test0.txt 100 1&
python3 train.py ../../data/rnn_res/coarse_1_ ../../data/train/coarse_train1.txt.char_to_idx ../../data/train/coarse_train1.txt.word_to_idx ../../data/train/coarse_train1.txt.tag_to_idx ../../data/train/coarse_train1.txt.csv ../../data/test/coarse_test1.txt 100 2&
python3 train.py ../../data/rnn_res/coarse_2_ ../../data/train/coarse_train2.txt.char_to_idx ../../data/train/coarse_train2.txt.word_to_idx ../../data/train/coarse_train2.txt.tag_to_idx ../../data/train/coarse_train2.txt.csv ../../data/test/coarse_test2.txt 100 3&
python3 train.py ../../data/rnn_res/coarse_3_ ../../data/train/coarse_train3.txt.char_to_idx ../../data/train/coarse_train3.txt.word_to_idx ../../data/train/coarse_train3.txt.tag_to_idx ../../data/train/coarse_train3.txt.csv ../../data/test/coarse_test3.txt 100 4&
python3 train.py ../../data/rnn_res/coarse_4_ ../../data/train/coarse_train4.txt.char_to_idx ../../data/train/coarse_train4.txt.word_to_idx ../../data/train/coarse_train4.txt.tag_to_idx ../../data/train/coarse_train4.txt.csv ../../data/test/coarse_test4.txt 100 5&

python3 train.py ../../data/rnn_res/coarse_0_ ../../data/train/fine_train0.txt.char_to_idx ../../data/train/fine_train0.txt.word_to_idx ../../data/train/fine_train0.txt.tag_to_idx ../../data/train/fine_train0.txt.csv ../../data/test/fine_test0.txt 100 5&
python3 train.py ../../data/rnn_res/coarse_1_ ../../data/train/fine_train1.txt.char_to_idx ../../data/train/fine_train1.txt.word_to_idx ../../data/train/fine_train1.txt.tag_to_idx ../../data/train/fine_train1.txt.csv ../../data/test/fine_test1.txt 100 1&
python3 train.py ../../data/rnn_res/coarse_2_ ../../data/train/fine_train2.txt.char_to_idx ../../data/train/fine_train2.txt.word_to_idx ../../data/train/fine_train2.txt.tag_to_idx ../../data/train/fine_train2.txt.csv ../../data/test/fine_test2.txt 100 2&
python3 train.py ../../data/rnn_res/coarse_3_ ../../data/train/fine_train3.txt.char_to_idx ../../data/train/fine_train3.txt.word_to_idx ../../data/train/fine_train3.txt.tag_to_idx ../../data/train/fine_train3.txt.csv ../../data/test/fine_test3.txt 100 3&
python3 train.py ../../data/rnn_res/coarse_4_ ../../data/train/fine_train4.txt.char_to_idx ../../data/train/fine_train4.txt.word_to_idx ../../data/train/fine_train4.txt.tag_to_idx ../../data/train/fine_train4.txt.csv ../../data/test/fine_test4.txt 100 4&

python3 train.py ../../data/rnn_res/resistance_0_ ../../data/train/resistance_train0.txt.char_to_idx ../../data/train/resistance_train0.txt.word_to_idx ../../data/train/resistance_train0.txt.tag_to_idx ../../data/train/resistance_train0.txt.csv ../../data/test/resistance_test0.txt 100 1&
python3 train.py ../../data/rnn_res/resistance_1_ ../../data/train/resistance_train1.txt.char_to_idx ../../data/train/resistance_train1.txt.word_to_idx ../../data/train/resistance_train1.txt.tag_to_idx ../../data/train/resistance_train1.txt.csv ../../data/test/resistance_test1.txt 100 2&
python3 train.py ../../data/rnn_res/resistance_2_ ../../data/train/resistance_train2.txt.char_to_idx ../../data/train/resistance_train2.txt.word_to_idx ../../data/train/resistance_train2.txt.tag_to_idx ../../data/train/resistance_train2.txt.csv ../../data/test/resistance_test2.txt 100 3&
python3 train.py ../../data/rnn_res/resistance_3_ ../../data/train/resistance_train3.txt.char_to_idx ../../data/train/resistance_train3.txt.word_to_idx ../../data/train/resistance_train3.txt.tag_to_idx ../../data/train/resistance_train3.txt.csv ../../data/test/resistance_test3.txt 100 4&
python3 train.py ../../data/rnn_res/resistance_4_ ../../data/train/resistance_train4.txt.char_to_idx ../../data/train/resistance_train4.txt.word_to_idx ../../data/train/resistance_train4.txt.tag_to_idx ../../data/train/resistance_train4.txt.csv ../../data/test/resistance_test4.txt 100 5&
